name: CI
on: push

jobs:
  linux:
    name: build powerbox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: 
        chmod +x ./powerbox-build.sh
        ./powerbox-build.sh
      shell: bash
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: powerbox-build
        path: powerbox.tar.gz
