name: CI
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: sh "${GITHUB_WORKSPACE}/build-powerbox.sh"
