name: CI
on: push

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    steps:
    - name: build
      chmod +x ./build-powerbox.sh
      run: ./build-powerbox.sh"
